### ISSUE TITLE
Add a document app

### ISSUE THREAD

**Issue by emilkovacev** [makeopensource/makeopensource.org#13]
# Document App
Create a new app (named documents) with the following features:

- [ ] Upload files from within the admin panel
- [ ] View/hide/remove files from within the admin panel
- [ ] Display uploaded file at `/documents/<filename>`
- [ ] Display list of files at `/documents/`

(You should be good to fork this issue if you're working in a different app entirely)

**Comment by PotLid** [comment]
Hi, I'm Jun can I request for Assignee role?
