### ISSUE TITLE
Change makeopensource.com to makeopensource.org in link in about page

### ISSUE THREAD

**Issue by zackattackz** [makeopensource/makeopensource.org#8]
Just a small type I noticed. This is a good issue for a beginner to fork the repo, commit the change, and make a PR including the commit :)

**Comment by zackattackz** [comment]
Issue is at line 20 of templates/about/index.html

**Comment by AleenaSA** [comment]
hi, could you assign this to me?

**Comment by emilkovacev** [comment]
Are you able to assign yourself on the top right?–if not I can assign you (and then find a fix for that) 😁

**Comment by AleenaSA** [comment]
no, I don't see any option to assign on the top right :/

**Comment by emilkovacev** [comment]
Ok, I assigned you to the issue, I'll look into why you couldn't see that, good luck!

**Comment by AleenaSA** [comment]
Thanks, I have raised a PR for the typo fix.

**Comment by zackattackz** [comment]
Closing this due to #9 , congrats on your first PR @AleenaSA 🎉🎉
